language: rust
rust: nightly
os:
  - linux
  - osx
cache: cargo
sudo: false
script:
  - cargo build
  - cargo test -p mutagen-core # run unit tests first
  - cargo test -p mutagen-selftest # run integration tests
  - cargo test # run all (other) tests

  # run executable cargo-mutagen on test project
  - pushd examples/simple
  - cargo run --package cargo-mutagen
  - popd
  - pushd examples/feature-gated
  - cargo run --package cargo-mutagen -- --features with_mutagen
