[package]
name = "mutagen"
version = "0.2.0"
authors = ["Samuel Pilz <samuel.pilz@posteo.net>"]
edition = "2018"

[dependencies]
mutagen-transform = { path = "../mutagen-transform" }
mutagen-core = { path = "../mutagen-core" }

[lib]
doctest = false
