[package]
name = "mutagen-transform"
version = "0.2.0"
authors = ["power-fungus <samuel.pilz@posteo.net>"]
edition = "2018"

[dependencies]
mutagen-core = { path = "../mutagen-core" }
proc-macro2 = "1.0.1"

[lib]
proc_macro = true
doctest = false
test = false
