[package]
name = "example-with-integration-tests"
version = "0.2.0"
authors = ["Samuel Pilz <samuel.pilz@posteo.net>"]
edition = "2018"

[features]
mutationtest = ["mutagen"]

[dependencies]
mutagen = {path = "../../mutagen", optional = true}

[lib]
doctest = false
