[package]
name = "example-with-integration-tests"
version = "0.2.0"
authors = ["Samuel Pilz <samuel.pilz@posteo.net>"]
edition = "2018"

[dependencies]
mutagen = {path = "../../mutagen"}

[lib]
doctest = false
